PhotographPhotoBundle_home:
    pattern:  /accueil
    defaults: { _controller: PhotographPhotoBundle:Default:index }

PhotographPhotoBundle_contact:
    pattern:  /contact
    defaults: { _controller: PhotographPhotoBundle:Page:contact }
    
PhotographPhotoBundle_portfolio:
    pattern:  /portfolio
    defaults: { _controller: PhotographPhotoBundle:Page:portfolio, name: '' }
    
PhotographPhotoBundle_about:
    pattern:  /presentation
    defaults: { _controller: PhotographPhotoBundle:Page:about }
    
PhotographPhotoBundle_faq:
    pattern:  /faq
    defaults: { _controller: PhotographPhotoBundle:Page:faq }
    
PhotographPhotoBundle_sitemap:
    pattern:  /sitemap
    defaults: { _controller: PhotographPhotoBundle:Page:sitemap }
        
PhotographPhotoBundle_gallery:
    pattern:  /galerie
    defaults: { _controller: PhotographPhotoBundle:Page:gallery }
    
PhotographPhotoBundle_portfolio_post_pierre_et_angelique:
    pattern:  /portfolio/mariage/pierre-et-angelique
    defaults: { _controller: PhotographPhotoBundle:Page:portfolio, name: 'pierre-et-angelique' }