PhotographPhotoBundle_home:
    pattern:  /
    defaults: { _controller: PhotographPhotoBundle:Default:index }

PhotographPhotoBundle_contact:
    pattern:  /contact
    defaults: { _controller: PhotographPhotoBundle:Contact:index}
           
PhotographPhotoBundle_portfolio:
    pattern:  /portfolio
    defaults: { _controller: PhotographPhotoBundle:Page:portfolio, name: '' }
    
PhotographPhotoBundle_about:
    pattern:  /presentation
    defaults: { _controller: PhotographPhotoBundle:Page:about }
    
PhotographPhotoBundle_faq:
    pattern:  /faq
    defaults: { _controller: PhotographPhotoBundle:Page:faq }

PhotographPhotoBundle_links:
    pattern:  /liens
    defaults: { _controller: PhotographPhotoBundle:Page:links }
    
PhotographPhotoBundle_prestations:
    pattern:  /prestations
    defaults: { _controller: PhotographPhotoBundle:Page:prestations }
    
PhotographPhotoBundle_sitemap:
    pattern:  /sitemap
    defaults: { _controller: PhotographPhotoBundle:Page:sitemap }
    
PhotographPhotoBundle_portfolio_wedding_post:
    pattern:  /portfolio/mariage/{name}
    defaults: { _controller: PhotographPhotoBundle:Page:portfolio}

PhotographPhotoBundle_portfolio_post:
        pattern:  /portfolio/{name}
        defaults: { _controller: PhotographPhotoBundle:Page:portfolio}

PhotographPhotoBundle_gallery:
    pattern:  /galeries/{name}
    defaults: { _controller: PhotographPhotoBundle:Page:gallery }

PhotographPhotoBundle_client:
    pattern:  /espace-client/{client}
    defaults: { _controller: PhotographPhotoBundle:Client:index }

#fake routes to trick google

PhotographPhotoBundle_googleFakePageLuxembourg:
    pattern:  /photographe-mariage/luxembourg
    defaults: { _controller: PhotographPhotoBundle:Page:googleFakePageLuxembourg}
PhotographPhotoBundle_googleFakePageLorraine:
        pattern:  /photographe-mariage/lorraine
        defaults: { _controller: PhotographPhotoBundle:Page:googleFakePageLorraine}
PhotographPhotoBundle_googleFakePageAlsace:
        pattern:  /photographe-mariage/alsace
        defaults: { _controller: PhotographPhotoBundle:Page:googleFakePageAlsace}
PhotographPhotoBundle_googleFakePageBelgique:
        pattern:  /photographe-mariage/belgique
        defaults: { _controller: PhotographPhotoBundle:Page:googleFakePageBelgique}